### ISSUE TITLE
Build fails with certificate issue

### ISSUE THREAD

**Issue by proever** [runfalk/synology-wireguard#109]
Hi there, I am trying to build from source for my DS220+/DSM 7.0 (installing the available release gives "Invalid file format").

The command I am running is
```
sudo docker run --rm --privileged --env PACKAGE_ARCH=geminilake --env DSM_VER=7.0 -v $(pwd)/artifacts:/result_spk -v $(pwd)/tarballs:/toolkit_tarballs synobuild
```

The build is failing with the following error
```
wget https://netfilter.org/projects/libmnl/files/libmnl-1.0.4.tar.bz2
--2021-10-08 06:28:17--  https://netfilter.org/projects/libmnl/files/libmnl-1.0.4.tar.bz2
Resolving netfilter.org (netfilter.org)... 92.243.18.11, 2001:4b98:dc0:43:216:3eff:fe87:a456
Connecting to netfilter.org (netfilter.org)|92.243.18.11|:443... connected.
ERROR: cannot verify netfilter.org's certificate, issued by 'CN=R3,O=Let\'s Encrypt,C=US':
  Unable to locally verify the issuer's authority.
To connect to netfilter.org insecurely, use `--no-check-certificate'.
Makefile:26: recipe for target 'libmnl-1.0.4.tar.bz2' failed
```

I saw that you attempt to mitigate this issue by copying the certificates into the build env on L89 of `build.sh`, but it doesn't seem to be working for some reason. Any ideas why this might be the case?

**Comment by stepanovdg** [comment]
The same issue on apollolake 
Tried on mac, fedora 34, and on synology itself. (((

**Comment by stepanovdg** [comment]
Tried add 
 --no-check-certificate
 into all calls of wget in Makefile.
 That helped.

**Comment by stepanovdg** [comment]
Also in dockerfile root ca are installed but I am not sure about openssl version. 
1.0.x. has troubles with ISRG Root X1 so maybe updating openssl to 1.1.x would resolve this issue.

**Comment by systemcrash** [comment]
Alright people? This could be a workable fix:
https://stackoverflow.com/a/69407725
or
https://stackoverflow.com/a/69440350
