### ISSUE TITLE
DS214+ supported?

### ISSUE THREAD

**Issue by mgoodings** [runfalk/synology-wireguard#11]
I have a DS214+ running Linux 3.2.40, will this work?

```$ uname -a
Linux FoxStation 3.2.40 #24922 SMP Fri May 10 02:48:25 CST 2019 armv7l GNU/Linux synology_armadaxp_ds214+```

**Comment by runfalk** [comment]
No, unfortunately your kernel version is too old. You need at least 3.10, see #8.

**Comment by vitrlink** [comment]
Hello, i have the DS214+ and it works well with the Tailscale package 
The tailscale build is based on synology-wireguard, according to https://github.com/tailscale/tailscale-synology

I have DSM7
Linux nas 3.2.101 #41890 SMP Thu Jul 15 03:42:09 CST 2021 armv7l GNU/Linux synology_armadaxp_ds214+

**Comment by runfalk** [comment]
> The tailscale build is based on synology-wireguard, according to https://github.com/tailscale/tailscale-synology

That's not quite right. The _build process_ was based on this project. Tailscale uses a userland wireguard implementation so it doesn't depend on a certain kernel version.
