### ISSUE TITLE
Error when activating wg interface on DS220j

### ISSUE THREAD

**Issue by OfficialMuffin** [runfalk/synology-wireguard#126]
**Description**
I have successfully checked and built the wireguard package for my particular NAS. When activating the interface with `wg-quick`, an error shows that resolvconf not found.

**Steps to reproduce**
```
$ ssh user@nas
$ sudo wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.6.0.8/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
/usr/local/bin/wg-quick: line 32: resolvconf: command not fo
und
[#] ip link delete dev wg0
```

**Expected behavior**
Wireguard successfully activates the wg0 interface and connects to peer with no error.

**Synology NAS model**
DS220j 

**wg0.conf**
```
[Interface]
PrivateKey = REDACTED
Address = 10.6.0.8/24
DNS = 10.6.0.1

[Peer]
PublicKey = REDACTED
PresharedKey = REDACTED
Endpoint = REDACTED:51820
AllowedIPs = 0.0.0.0/0, ::0/0
```

**Comment by OfficialMuffin** [comment]
Found the same issue  [here]https://github.com/runfalk/synology-wireguard/issues/4). However, I run a PiHole server on that DNS IP. I would much rather keep the config as it is as my PiHole has a recursive DNS resolver.

**Comment by OfficialMuffin** [comment]
If I remove the DNS from wg0.conf. I get a different error. This time with iptables.

```
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.6.0.8/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] wg set wg0 fwmark 51820
[#] ip -6 route add ::/0 dev wg0 table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] ip6tables-restore -n
ip6tables-restore v1.8.3 (legacy): ip6tables-restore: unable
 to initialize table 'raw'

Error occurred at line: 1
```

**Comment by OfficialMuffin** [comment]
I have found a workaround by deleting the line `AllowedIPs = 0.0.0.0/0, ::0/0`, the wireguard interface sucessfully starts with no errors and handshakes are sent and received by the other peer.

`sudo wg` command shows:

```
interface: wg0
  public key: REDACTED
  private key: (hidden)
  listening port: 51826

peer: REDACTED
  preshared key: (hidden)
  endpoint: REDACTED:51820
  allowed ips: (none)
```

**Comment by OfficialMuffin** [comment]
Ok, I have specified a specific IP, `10.6.0.1/24` in the `AllowedIPs` line. Pinging the wireguard peer works!
However, I get a warning:

```
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
Warning: AllowedIP has nonzero host part: 10.6.0.1/24
[#] ip -4 address add 10.6.0.8/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
```
Not too sure if this is fine the way it is. Please advise

**Comment by loons1k** [comment]
try: AllowedIPs = 0.0.0.0/1

**Comment by OfficialMuffin** [comment]
> try: AllowedIPs = 0.0.0.0/1

Please read my last comment. There is a problem with pinging devices.

**Comment by OfficialMuffin** [comment]
I have fixed the issue. It seems like the wireguard did not like the Endpoint I set, which was my DDNS. I tried changing the DDNS name to an IP address but still did not work. Finally, I tried setting it to the private IP of the local wireguard "server" peer of 192.168.0.25 and it worked!  Now I just wish that DNS could be set for PiHole to work.

**Comment by OfficialMuffin** [comment]
Ah, I am now unable to access the web interface for synology and SSH does not work. However, pinging the synology does from another peer which I could not do before. Do I have to allow these connections through the synology firewall which is currently disabled?

**Comment by runfalk** [comment]
Sounds like you have locked yourself out by only accepting connections through the wireguard interface. `AllowedIPs = 0.0.0.0/0, ::0/0` makes it so that you can only run traffic over the wireguard interface.

**Comment by bdlow** [comment]
@OfficialMuffin, you may already be aware of this but to be sure: your original problem was likely due to including a `DNS` line; per the synology-wireguard README: wg's DNS option is not supported.
i.e. the reason the tunnel didn't come up is that wg-quick tore it down when the resolvconf step failed.
