### ISSUE TITLE
Support platform 88f628x

### ISSUE THREAD

**Issue by ctaque** [runfalk/synology-wireguard#129]
My Nas (DS411slim) is platform version 88f628x and is not supported :  

```
sudo docker run --rm --privileged --env PACKAGE_ARCH=88f628x --env DSM_VER=6.2 -v $(pwd)/artifacts:/result_spk synobuild

WireGuard version:        1.0.20211208
WireGuard tools version:  1.0.20210914
libmnl version:           1.0.4

Cloning into 'pkgscripts-ng'...

PlatformNotAvailableError:
[88f628x] is not available platform.

[ERROR] pkgscripts-ng/EnvDeploy -p 88f628x -v 6.2 failed!
cp: cannot create regular file '/build_env/ds.88f628x-6.2/etc/ssl/certs/': No such file or directory
```

**Comment by runfalk** [comment]
So this package can only support archs that Synology provides a toolchain for. The full list is here https://sourceforge.net/projects/dsgpl/files/toolkit/DSM7.0/ (version 7.0) and https://sourceforge.net/projects/dsgpl/files/toolkit/DSM6.2/ (version 6.2). It seems they don't provide a 7.0 version for this device though. As far as I can see they don't provide a toolchain for this arch so there is nothing I can do to support your device.
