### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jimski427** [runfalk/synology-wireguard#13]
I have the synology ds 216+II, wondering if this is compatible? i don't see it on the list the kernel verzion is 3.10.105. Looks like it has an Intel Celeron N3060

**Comment by runfalk** [comment]
It seems to be Braswell based. It may work, you can try the pkg I made here: https://github.com/runfalk/synology-wireguard/issues/9#issuecomment-493748945

Let me know if it works.
