### ISSUE TITLE
The package is not compatible with DSM 7.1 on armada38x 

### ISSUE THREAD

**Issue by fabiov64** [runfalk/synology-wireguard#143]
**Description**
After upgrading to DSM 7.1, running wg-quick causes a segmentation fault
**Steps to reproduce**
```
$ ssh user@nas
$ sudo wg-quick up wg0

the result is: /usr/local/bin/wg-quick: line 30: 16471 Segmentation fault      "$@"

Then the system becomes unstable and it cannot be shut down properly. Interrupting the power supply is the only way to restart.

**Synology NAS model**
DS216j

**wg0.conf**

[Interface]
ListenPort = XXXXX
Address = 10.100.100.1/24
PrivateKey = 
PostUp =  iptables -t nat -I POSTROUTING -o eth0 -j MASQUERADE
PreDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = 
AllowedIPs = 10.100.100.2/32

**Comment by mandre00** [comment]
There is no toolkit for DSM 7.1 available yet.

https://archive.synology.com/download/ToolChain/toolkit

**Comment by fabiov64** [comment]
Yes, I know. But I wanted to warn people not to update DMS if they need wireguard.

**Comment by regunakyle** [comment]
I think Synology explicitly mentioned that I cannot downgrade DSM 7.1 (maybe implying that downgrading has consequences). Am I stuck with OpenVPN for now?

**Comment by fabiov64** [comment]
> I think Synology explicitly mentioned that I cannot downgrade DSM 7.1 (maybe implying that downgrading has consequences). Am I stuck with OpenVPN for now?

Yes, you're. Until the toolkit will be released and the compilation of the package will be possible.

**Comment by digitalface** [comment]
> Yes, I know. But I wanted to warn people not to update DMS if they need wireguard.

Thank you for the warning - I had downloaded the 7.1 update for my DS220+ and was about to apply it before checking here for any issues. I use WG daily so can't do without it. I'll stay on 7.0 for now.

**Comment by allexoll** [comment]
FIY the toolkit is now available for 7.1

**Comment by digitalface** [comment]
you have to change version in a couple of places but most importantly build.sh to grab the 7.1 version of pkgscripts. I'm compiling a 7.1 version (hopefully) of Wireguard for DS220+ as we speak.

**Comment by fabiov64** [comment]
> you have to change version in a couple of places but most importantly build.sh to grab the 7.1 version of pkgscripts. I'm compiling a 7.1 version (hopefully) of Wireguard for DS220+ as we speak.

I tried, but probably I did not change the right files. May you share more details ?

**Comment by digitalface** [comment]
After cloning the .git to synology-wireguard, alter the line in build.sh under "Fetch Synology toolchain" to be clone_args="-b DSM7.1" . Under release.sh add "7.1" to the VERSIONS string. Then do "sudo docker build -t synobuild . " and follow instructions for your ARCH

**Comment by fabiov64** [comment]
I already tried that, but the compilation cannot finish:

Cloning into 'pkgscripts-ng'...
[2022-06-01 16:23:02,692] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.1&platform=base
[2022-06-01 16:23:18,686] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.1&platform=armada38x
[2022-06-01 16:23:28,462] INFO: tar -xhf /toolkit_tarballs/base_env-7.1.txz -C /build_env/ds.armada38x-7.1
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "//pkgscripts-ng/EnvDeploy", line 77, in <module>
    main(sys.argv[1:])
  File "//pkgscripts-ng/EnvDeploy", line 71, in main
    toolkit.deploy()
  File "/pkgscripts-ng/include/python/pkgdeploy.py", line 201, in deploy
    self.deploy_base_env(platform)
  File "/pkgscripts-ng/include/python/pkgdeploy.py", line 242, in deploy_base_env
    self.__extract__(
  File "/pkgscripts-ng/include/python/pkgdeploy.py", line 239, in __extract__
    subprocess.check_call(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xhf', '/toolkit_tarballs/base_env-7.1.txz', '-C', '/build_env/ds.armada38x-7.1']' returned non-zero exit status 2.

**Comment by digitalface** [comment]
I've managed to successfully build and install Wireguard for DSM 7.1 on my DS220+ now and also was able to build an apollolake package for my friends DS218+

Incidentally I tried building your armada38x arch and it failed with an error, not the same error as yours but it didn't complete.

**Comment by fabiov64** [comment]
BTW: I'm non more able to compile neither the 7.0 version. I always get the same error as above. I tried on both a MacOs and Ubuntu x64 machines. Probably something changed in the EnvDeploy script or in the docker defaults and the tarballs files cannot be accessed

**Comment by mandre00** [comment]
Ok I found the problem. It's the wrong **pkgscripts-ng** version.

To Fix this do the following in build.sh

    diff --git a/build.sh b/build.sh
    index 4a1afc0..57a2d32 100755
    --- a/build.sh
    +++ b/build.sh
    @@ -36,7 +36,7 @@ if [[ ! -d /pkgscripts-ng ]] || [ -z "$(ls -A /pkgscripts-ng)" ]; then
         clone_args=""
         # If the DSM version is 7.0, use the DSM7.0 branch of pkgscripts-ng
         if [[ "$DSM_VER" =~ ^7\.[0-9]+$ ]]; then
    -        clone_args="-b DSM7.0"
    +        clone_args="-b DSM$DSM_VER"
             export PRODUCT="DSM"
         fi
         git clone ${clone_args} https://github.com/SynologyOpenSource/pkgscripts-ng

after that rebuild the image

    docker build -t synobuild .

Now you should be able to build the module with version 7.1

**Comment by fabiov64** [comment]
I solved the issue of above. The docker image created following the instructions does not contain the xz executable and then the tar command fails. In oder to fix, I modified the Dockerfile, adding the xz-utils to the list of packages to be installed. I'm compiling on Mac OS or on Windows. After doing that, I was able to compile the 7.0 on armada38x. In the past it worked without any modification. I suspect something changed in the ubuntu image used as base.

**Comment by Jerdle** [comment]
@digitalface could you link your DS220+ 7.1 build? I made the same changes you suggested but keep getting this error even running as root:

`/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied`
`ERROR: This script must be run as root`

**Comment by digitalface** [comment]
> @digitalface could you link your DS220+ 7.1 build? I made the same changes you suggested but keep getting this error even running as root:
> 
> `/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied` `ERROR: This script must be run as root`
> 
> Just bought my NAS so no choice on DSM version :(

Sure, I'll do it tomorrow when I'm back at my computer.

**Comment by digitalface** [comment]
> @digitalface could you link your DS220+ 7.1 build? I made the same changes you suggested but keep getting this error even running as root:
> 
> `/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied` `ERROR: This script must be run as root`
> 
> Just bought my NAS so no choice on DSM version :(

@jerdle do you still need this?

**Comment by Jerdle** [comment]
@digitalface no finally got it to build on a MacOS.. thanks though

**Comment by james2406** [comment]
> after that rebuild the image

@mandre00 Completely forgot to do that, so thanks for adding that.

**Comment by jollyjester** [comment]
Just to add if you are building on the synology then this solved it for me
https://github.com/runfalk/synology-wireguard/issues/88#issuecomment-1026355820

**Comment by kingname** [comment]
> 

bro, Please tell me how to install wireguard on DS220+ with DSM 7.1

**Comment by fabiov64** [comment]
You need to compile it, after modifying the build.sh as described here above. After the compilation, you can manually install it using the Package Manager of DSM. For the compilation, please follow the official instructions. You can compile on whatever platform you have (Windows, Linux, MacOs) after installing Docker.

**Comment by haldi4803** [comment]
no preBuild packages around somewhere?
