### ISSUE TITLE
Compile Error DS220+/DSM 7.0

### ISSUE THREAD

**Issue by kaganae** [runfalk/synology-wireguard#144]
**Description**
Followed the instructions but am getting an error on my DS220+ (genilake) under DSM 7.0.1. Am I doing something wrong?

**Steps to reproduce**
bash-4.4$ git clone https://github.com/runfalk/synology-wireguard.git
Cloning into 'synology-wireguard'...
remote: Enumerating objects: 315, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 315 (delta 18), reused 44 (delta 13), pack-reused 262
Receiving objects: 100% (315/315), 99.37 KiB | 1.99 MiB/s, done.
Resolving deltas: 100% (162/162), done.

bash-4.4$ cd synology-wireguard

bash-4.4$ git fetch origin pull/71/head:DSM7.0
From https://github.com/runfalk/synology-wireguard
 * [new ref]         refs/pull/71/head -> DSM7.0

bash-4.4$ git checkout DSM7.0
Switched to branch 'DSM7.0'

bash-4.4$ sudo docker build -t synobuild .
Password: 
Sending build context to Docker daemon  256.5kB
Step 1/6 : FROM ubuntu:latest
 ---> 3f4714ee068a
Step 2/6 : VOLUME [ "/toolkit_tarballs" ]
 ---> Using cache
 ---> 62fb123b8c10
Step 3/6 : ENV IS_IN_CONTAINER 1
 ---> Using cache
 ---> b14195cfd7d9
Step 4/6 : RUN apt-get update  && apt-get -qy install git python3 wget ca-certificates
 ---> Using cache
 ---> 6adce15c2b76
Step 5/6 : COPY . /source/WireGuard
 ---> 0a1a2c899a58
Step 6/6 : ENTRYPOINT exec /source/WireGuard/build.sh
 ---> Running in cb800ea6766a
Removing intermediate container cb800ea6766a
 ---> ec808f81a072
Successfully built ec808f81a072
Successfully tagged synobuild:latest

bash-4.4$ mkdir artifacts

bash-4.4$ sudo docker run --rm --privileged --env PACKAGE_ARCH=geminilake --env DSM_VER=7.0 -v $(pwd)/artifacts:/result_spk synobuild
Password: 
WireGuard version:        1.0.20211208
WireGuard tools version:  1.0.20210914
libmnl version:           1.0.5

Cloning into 'pkgscripts-ng'...
[2022-04-25 20:02:26,573] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.0&platform=base
[2022-04-25 20:02:36,390] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.0&platform=geminilake
**[2022-04-25 20:02:43,787] INFO: tar -xhf /toolkit_tarballs/base_env-7.0.txz -C /build_env/ds.geminilake-7.0
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "//pkgscripts-ng/EnvDeploy", line 77, in <module>
    main(sys.argv[1:])
  File "//pkgscripts-ng/EnvDeploy", line 71, in main
    toolkit.deploy()
  File "/pkgscripts-ng/include/python/pkgdeploy.py", line 201, in deploy
    self.deploy_base_env(platform)
  File "/pkgscripts-ng/include/python/pkgdeploy.py", line 242, in deploy_base_env
    self.__extract__(
  File "/pkgscripts-ng/include/python/pkgdeploy.py", line 239, in __extract__
    subprocess.check_call(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xhf', '/toolkit_tarballs/base_env-7.0.txz', '-C', '/build_env/ds.geminilake-7.0']' returned non-zero exit status 2.**

**Comment by oohlaf** [comment]
Have a look at this tree here, adjust your model in the release script and build it: https://github.com/oohlaf/synology-wireguard/tree/fixes

**Comment by kaganae** [comment]
Sorry, don't see any reference to model in the release.sh script - only architecture, which is geminilake. Thoughts?

**Comment by digitalface** [comment]
@kaganae I had the same issue (same box, same DSM) - I took oohlaf's 'fix' and now am able to compile the .spk using a linux VM (not the synology unit itself).

I tried replacing the runfalk url with the below but it seems the oohlaf fixes aren't in that .git, so if you download the zip file and extract it to the synology-wireguard folder instead and carry on.

So, download this: https://github.com/oohlaf/synology-wireguard/archive/refs/heads/fixes.zip
Extract the contents to /synology-wireguard on you linux host
Run: 
cd synology-wireguard/
sudo docker build -t synobuild 

Finally run:
sudo docker run --rm --privileged --env PACKAGE_ARCH=geminilake --env DSM_VER=7.0 -v $(pwd)/artifacts:/result_spk synobuild





Doesn't work >
(
git clone https://github.com/oohlaf/synology-wireguard.git
cd synology-wireguard/
sudo docker build -t synobuild .)

**Comment by kaganae** [comment]
That did it. Thank you!
