### ISSUE TITLE
DS920+ Geminilake Issues

### ISSUE THREAD

**Issue by MGoulding98** [runfalk/synology-wireguard#153]
Hello, I have followed the steps to compile since I am on DSM 7.0 and while that appeared to be successful I cannot actually build successfully. The build command I use is:
```
sudo docker run --rm --privileged --env PACKAGE_ARCH=geminilake --env DSM_VER=7.0 -v $(pwd)/artifacts:/result_spk synobuild
```

These are the last few lines of my output:
```
tar: usr/bin/yarnpkg: Cannot change mode to rwxrwxrwx: No such device or address
tar: usr/bin/npx: Cannot change mode to rwxrwxrwx: No such device or address
tar: etc/localtime: Cannot change mode to rwxrwxrwx: No such device or address
tar: etc/mtab: Cannot change mode to rwxrwxrwx: No such device or address
tar: .eslintrc.json: Cannot change mode to rwxrwxrwx: No such device or address
tar: root/.yarnrc: Cannot change mode to rwxrwxrwx: No such device or address
tar: root/.npmrc: Cannot change mode to rwxrwxrwx: No such device or address
tar: root/.jshintrc: Cannot change mode to rwxrwxrwx: No such device or address
tar: .babelrc: Cannot change mode to rwxrwxrwx: No such device or address
tar: var/lock: Cannot change mode to rwxrwxrwx: No such device or address
tar: var/run: Cannot change mode to rwxrwxrwx: No such device or address
tar: dev/stderr: Cannot change mode to rwxrwxrwx: No such device or address
tar: dev/stdin: Cannot change mode to rwxrwxrwx: No such device or address
tar: dev/fd: Cannot change mode to rwxrwxrwx: No such device or address
tar: dev/cdrom: Cannot change mode to rwxrwxrwx: No such device or address
tar: dev/stdout: Cannot change mode to rwxrwxrwx: No such device or address
tar: Exiting with failure status due to previous errors
Traceback (most recent call last):
  File "//pkgscripts-ng/EnvDeploy", line 77, in <module>
    main(sys.argv[1:])
  File "//pkgscripts-ng/EnvDeploy", line 71, in main
    toolkit.deploy()
  File "/pkgscripts-ng/include/python/pkgdeploy.py", line 201, in deploy
    self.deploy_base_env(platform)
  File "/pkgscripts-ng/include/python/pkgdeploy.py", line 242, in deploy_base_env
    self.__extract__(
  File "/pkgscripts-ng/include/python/pkgdeploy.py", line 239, in __extract__
    subprocess.check_call(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xhf', '/toolkit_tarballs/base_env-7.0.txz', '-C', '/build_env/ds.geminilake-7.0']' returned non-zero exit status 2.
```
There are hundreds of these errors before it as well. Is this a permissions issue somehow even though I'm running with sudo? Thanks!

**Comment by spcqike** [comment]
i can't help you compile, but maybe a pre-compiled .spk is enough :)

https://github.com/runfalk/synology-wireguard/issues/93#issuecomment-922057387

**Comment by MGoulding98** [comment]
Thank you so much!

**Comment by MGoulding98** [comment]
Update: Unfortunately it gave me the "invalid format error" and it looks like a few other people have had that issue in that thread. I'll just have to wait for the 7.0 packages to be released officially. Thanks anyways!

**Comment by spcqike** [comment]
Hi 

In this case have a look at my post 
https://github.com/runfalk/synology-wireguard/issues/149#issue-1230646664

maybe this also works for you.

**Comment by MGoulding98** [comment]
I actually saw that post as well, but I'm running wireguard via docker so that doesn't apply. My only thought is that the other people are right and Synology changed something in a recent update that is affecting certain systems.

**Comment by MGoulding98** [comment]
While I didn't have to follow your steps exactly, it did remind me that I had not uninstalled the old wireguard spk that I had used on DSM 6.0. Once I removed that the one you linked worked just fine. 

Not sure if having that installed is why I couldn't compile before, but since it's working I'm going to close this anyways. Appreciate your help.
