### ISSUE TITLE
Upgrading wireguard version

### ISSUE THREAD

**Issue by antoniy** [runfalk/synology-wireguard#17]
Hello,

What is the correct way to upgrade to a newer wireguard version and compile the package indicating that version?

Best Regards,
Antoniy

**Comment by Cyberwizzard** [comment]
Look at #16 - I upgraded there to a newer version, did not fix the issues I had though so I do not know if newer versions work on DSM correctly... (see #10)

**Comment by runfalk** [comment]
Just like @Cyberwizzard's solution you do it like this: https://github.com/runfalk/synology-wireguard/commit/09acbb25cd0bbc529d58f3906b8354aa653df1da. I've updated the package to 0.0.20190702 now.
