### ISSUE TITLE
What is specific to Synology when configuring WireGuard?

### ISSUE THREAD

**Issue by Spass1966** [runfalk/synology-wireguard#3]
I'm following this [guide](https://www.ckn.io/blog/2017/11/14/wireguard-vpn-typical-setup/) when setting up WireGuard and I have all the tools needed except when I reach 

> We also want to ensure that the rules remain persistent across reboots.

Specific packages are required here that we don't have available to us as Synology owners. Have you followed a different guide? Did I even need the `iptables` rules?

**Comment by runfalk** [comment]
I don't use any `iptables` configuration. However, I don't use the NAS for tunneling traffic to the internet. Maybe it's required for that.

This is the best guide I found: https://try.popho.be/wg.html (which doesn't talk about `iptables`)

**Comment by Spass1966** [comment]
Well dang I did my best to tunnel all my traffic through but no luck. At least on my Android device, I can't resolve any web addresses.

**Comment by runfalk** [comment]
You may want to try the new release. It adds `iptables` support:

https://github.com/runfalk/synology-wireguard/releases/tag/0.0.20190227-2

This should make
