### ISSUE TITLE
Encountering error upon launching wg-quick up

### ISSUE THREAD

**Issue by harmfulmushroom** [runfalk/synology-wireguard#4]
Using your directions I am successful in running everything on my diskstation until I hit this message trying to use wg-quick up:

/usr/local/bin/wg-quick: line 31: resolvconf: command not found

This seemed to be a big issue with various ubuntu images, but unlike them I cannot run their fix sudo apt-get install resolvconf.

My unit is a DS1019+, I used your pre-configured apollolake SPK as my platform should be compatible going off the table.  Any idea's on how to resolve this?

**Comment by runfalk** [comment]
That's concerning. Which DSM version are you using?

Maybe @Spass1966 or @ShagoY who have Apollolake can helt you out

**Comment by ShagoY** [comment]
"resolvconf" is only used when using the DNS variable in the Wireguard configuration file.
And since I don't use it... No problem :-D

**Comment by harmfulmushroom** [comment]
Very cool, yeah that does appear to be what differs between my config file and a few others I've been reviewing (not sure how I missed this until now).  I'll play around with things on my end and see if I can't get it working, either by removing the DNS portion of my config or re-configuring the server to not specify a DNS.  Thanks!

**Comment by runfalk** [comment]
Thank you @ShagoY.

Let me know if everything else works as expected @harmfulmushroom and I'll add you drive to the compatibility table.

**Comment by harmfulmushroom** [comment]
Sure thing @runfalk, I removed the DNS portion of my config file and all loaded successfully.  I now see the new interface listed so I should be good to go now!

Can confirm DS1019+ is compatible.

**Comment by runfalk** [comment]
Great! I've updated the compatibility table.

I'll close this issue for now. `resolveconf` support might be something to look into later, but that will have to be a separate issue.

**Comment by thisis-mental** [comment]
Hello @harmfulmushroom 
How did you make it work without the DNS section?
I'm using a wireguard configuration from my VPN provider and it's part of the config.
Thanks!

**Comment by runfalk** [comment]
I think you should be able to leave it out. I _think_ the consequence may be that the DNS requests do not go through your VPN provider. This means that someone may see which hosts you are connecting to, but not the traffic passed to them. Depending on your use case this may or may not be a problem.

**Comment by thisis-mental** [comment]
On my side, it doesn't work without the DNS. I can't ping anything.
