### ISSUE TITLE
How do I tell if the NAS is using the WireGuard connection?

### ISSUE THREAD

**Issue by spartanhooah** [runfalk/synology-wireguard#41]
**Description**
I followed the instructions in the readme, but I have no idea how to tell if it actually stuck. What can I do to check?

**Expected behavior**
Some way to know if the WireGuard connection is running correctly.

**Synology NAS model**
DS218+

**wg0.conf**
```
[Interface]
PrivateKey = 
Address = 10.19.49.7/24 ,fd9d:bc11:4021::7/48
DNS =  172.16.102.174, fd00::66ae

[Peer]
PublicKey = 
PresharedKey = 
AllowedIPs = 0.0.0.0/0,::/0
Endpoint = 138.197.199.252:51820
```

If there are multiple peers, include their configuration too.

**Comment by runfalk** [comment]
Can't remember if curl is built in or not. But if it is you can do `curl ifconfig.co` on the NAS and if the IP is the one of your WireGuard server you're probably OK. If have multiple clients you can also try to ping one of them using their WireGuard IP.

**Comment by spartanhooah** [comment]
Hm, that got me an error, so something's not right.

**Comment by runfalk** [comment]
Closing this since the question has been answered.
