### ISSUE TITLE
/usr/local/bin/wg-quick: line 32: resolvconf: command not found

### ISSUE THREAD

**Issue by bachrc** [runfalk/synology-wireguard#56]
**Description**
I followed the instructions on my DS918+, and when I wanna trigger the wg-quick, it doesn't find resolvconf on my synology.

```
sh-4.3# wg-quick up wg0-client
Warning: `/etc/wireguard/wg0-client.conf' is world accessible
[#] ip link add wg0-client type wireguard
[#] wg setconf wg0-client /dev/fd/63
[#] ip -4 address add 10.6.0.4/24 dev wg0-client
[#] ip link set mtu 1420 up dev wg0-client
[#] resolvconf -a wg0-client -m 0 -x
/usr/local/bin/wg-quick: line 32: resolvconf: command not found
[#] ip link delete dev wg0-client
sh-4.3#
```

Seems that I can't find resolvconf anywhere on my NAS. How should we install it ?

**Comment by bachrc** [comment]
Aaaaaaand this was because I had "DNS" on my wireguard configuration ! This is written in the README, I just don't know how to read. Sorry !

**Comment by alexxsanya** [comment]
@bachrc check out the solution in here - https://github.com/StreisandEffect/streisand/issues/1434, it helped me resolve mine

**Comment by xd19861224** [comment]
i have same error
