### ISSUE TITLE
DS1815+: iproute2 too old

### ISSUE THREAD

**Issue by yitzhaq** [runfalk/synology-wireguard#6]
I've tried using the avoton package on a DS1815+ running DSM 6.2.2. Running wg-quick up fails on setting suppress_prefixlength to 0 on the main IPv6 table:

```
# wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip address add n.n.n.n dev wg0
[#] ip address add nnnn:nnnn:nnnn:nnnn::nnn/128 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] wg set wg0 fwmark 51820
[#] ip -6 route add ::/0 dev wg0 table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
Error: argument "suppress_prefixlength" is wrong: Failed to parse rule type
[#] ip -6 rule delete table 51820
[#] ip link delete dev wg0
```

According to Jason, this is caused by the version of iproute2 being too old:

https://lists.zx2c4.com/pipermail/wireguard/2018-April/002687.html

I don't quite understand how this should be different from 6.2 running on DS1817+ where it supposedly works, but..

AFAICT the kernel should be recent enough, just about:

```
# uname -a
Linux nasse 3.10.105 #24922 SMP Thu Mar 28 11:04:28 CST 2019 x86_64 GNU/Linux synology_avoton_1815+

```
But iproute2 is rather old:

```
# ip -V
ip utility, iproute2-ss130716
```

What do you reckon would be the best way around this? I tried removing all IPv6 addresses from the config as a test, but it still wants to mess with the prefixlength.

**Comment by runfalk** [comment]
What does your wg0.conf look like? With and without IPv6 addresses. Maybe there is something that's unsupported that nobody has tried yet.

**Comment by yitzhaq** [comment]
Nothing too fancy.

```
# cat /etc/wireguard/wg0.conf 
[Interface]
Address = nnn.nnn.nnn.nnn, aaaa:bbbb:cccc:dddd::eee/128
#Address = nnn.nnn.nnn.nnn
PrivateKey = redacted
ListenPort = 51820
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o bond0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o bond0 -j MASQUERADE

[Peer]
PublicKey = redacted
AllowedIPs = 0.0.0.0/0, ::/0
#AllowedIPs = 0.0.0.0/0
Endpoint = endpoing.example.com:51820
PersistentKeepalive = 25
```
I haven't played around with it too much, but the interface comes up without reported errors on Ubuntu 18.10 with iproute2-ss180813 (4.18.0).

**Comment by runfalk** [comment]
The thing that sticks out is the `bond0` device name. My config looks like this:

```
[Interface]
Address = 10.0.1.1/16
PrivateKey = <redacted>
ListenPort = 15000
PostUp   = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = <redacted>
Endpoint = <redacted>:15000
AllowedIPs = 10.0.0.1/24
PersistentKeepalive = 25

[Peer]
PublicKey = <redacted>
AllowedIPs = 10.0.1.2/32
```

**Comment by runfalk** [comment]
Looking more deeply into your output from `wg-quick` it does seem to be IPv6-specific. So if you remove IPv6 from the configuration you should probably be fine I guess. I'll add something to the README about this being a known issue.

My `ip` version is the same as your:

```
$ ip -V
ip utility, iproute2-ss130716
```

**Comment by gromez** [comment]
I'm having the same issue with IPv4

```
# wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.10.0.101/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
Error: argument "suppress_prefixlength" is wrong: Failed to parse rule type
[#] ip -4 rule delete table 51820
[#] ip link delete dev wg0
```

I'm using my DS1515+ as client only, here is my config:

```
[Interface]
PrivateKey = <client secret key>
Address = 10.10.0.101/24

[Peer]
PublicKey = <server public key>
Endpoint = <server ip>:51820
AllowedIPs = 0.0.0.0/0
```

Is there something I'm doing wrong?

Thanks

**Comment by tangowithfoxtrot** [comment]
> I'm having the same issue with IPv4
> 
> ```
> # wg-quick up wg0
> [#] ip link add wg0 type wireguard
> [#] wg setconf wg0 /dev/fd/63
> [#] ip -4 address add 10.10.0.101/24 dev wg0
> [#] ip link set mtu 1420 up dev wg0
> [#] wg set wg0 fwmark 51820
> [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
> [#] ip -4 rule add not fwmark 51820 table 51820
> [#] ip -4 rule add table main suppress_prefixlength 0
> Error: argument "suppress_prefixlength" is wrong: Failed to parse rule type
> [#] ip -4 rule delete table 51820
> [#] ip link delete dev wg0
> ```
> 
> I'm using my DS1515+ as client only, here is my config:
> 
> ```
> [Interface]
> PrivateKey = <client secret key>
> Address = 10.10.0.101/24
> 
> [Peer]
> PublicKey = <server public key>
> Endpoint = <server ip>:51820
> AllowedIPs = 0.0.0.0/0
> ```
> 
> Is there something I'm doing wrong?
> 
> Thanks
> 
> **EDIT: found the problem**
> 
> If I set `AllowedIPs = 0.0.0.0/0` I have the problem, any way to forward all the traffic anyway?

I am having this issue as well. Commenting out the `AllowedIPs` line successfully brings the interface up, but I can't actually use it without allowing that range.

Does anyone know of a fix or a workaround?
