### ISSUE TITLE
Will there ever be Armada370/Armada375 support?

### ISSUE THREAD

**Issue by donmega** [runfalk/synology-wireguard#8]
Hi!

Couldn't find the question here :). Will there ever be support in the future for the Synology's that are running with the Armada370/Armada375 chipset? Or isn't this possible?

Thank you for your time and keep up the great work, devs!

**Comment by runfalk** [comment]
NASes with this chipset have a kernel version that is too old (3.2.40) to support WireGuard (requires 3.10). There are three possible ways of supporting it:

* Pressure Synology into releasing a new version of DSM with a newer kernel (the best way)
* Patching WireGuard to support older kernels (I think this is a lot of work)
* Virtualize another OS on your NAS and install WireGuard in that one. (I don't know if this works, and if it does it's probably pretty slow)

If someone from the community steps up and does the work with patching WireGuard I'll be happy to merge it.

To explicitly answer your question. It'll probably never work and I don't think it'll ever be possible.

**Comment by thiemo** [comment]
I am not questioning that the kernel is too old on these older boxes (3.2.101 on DSM 7). But then I ponder, how does the official [Tailscale package for Synology](https://tailscale.com/kb/1131/synology/) work on these older boxes (works on DS214+), since Tailscale uses wireguard as the underlying VPN protocol, right? I guess there must be some way.

**Comment by runfalk** [comment]
They are running WireGuard in userspace. I went to their GitHub to confim and they just package some statically linked binaries written in Go. This repository will only package the kernel module. There are other userspace implementations of WireGuard that may work on these older devices. I have never tried any of them myself though.
