### ISSUE TITLE
What about DS214play x86 ?

### ISSUE THREAD

**Issue by johacko** [runfalk/synology-wireguard#80]
it's not realy an issues, but DS214play is x86 with the Intel Atom CE5335
![image](https://user-images.githubusercontent.com/40550849/114182489-f3aca000-9942-11eb-98ee-4cfe5c8c5446.png)
![image](https://user-images.githubusercontent.com/40550849/114182568-0e7f1480-9943-11eb-9602-a8958afaa617.png)

also docker is not available on this NAS

**Comment by runfalk** [comment]
It seems to use the Evansport package architecture, which is untested but is likely working. You could try building it yourself:

```bash
git clone https://github.com/runfalk/synology-wireguard.git
cd synology-wireguard/
sudo docker build -t synobuild .
sudo docker run --rm --privileged --env PACKAGE_ARCH=evansport --env DSM_VER=6.2 -v $(pwd)/artifacts:/result_spk synobuild
```

You don't need docker on the NAS, just on the computer you use to build the package.

**Comment by johacko** [comment]
![image](https://user-images.githubusercontent.com/40550849/114215692-2fa52c80-9966-11eb-99e4-ec38a0cbee5c.png)

then I created artifacts directory myself and

![image](https://user-images.githubusercontent.com/40550849/114219691-4732e400-996b-11eb-93ca-3a90d7d68eee.png)

**Comment by Matige** [comment]
The minimum required kernel version for WireGuard is 3.10. The kernel version of your NAS is 3.2.40, so unfortunately, WireGuard will not work.

**Comment by runfalk** [comment]
Yeah, the kernel version is too old. The only way for it to be supported would be to use a userspace implementation (maybe https://github.com/cloudflare/boringtun or https://github.com/WireGuard/wireguard-rs could work?) or backport WireGuard to this version.
