### ISSUE TITLE
Can't install my fresh build SPK on DSM7

### ISSUE THREAD

**Issue by cyrinux** [runfalk/synology-wireguard#98]
**Description**
Hi, I maybe miss something, I'm able to build the SPK for DSM7/AppoloLake  (for a  DS918+ ).
I build it from docker on my laptop because i got error with docker from the NAS itself.
But then how to install it? I choose it from the "manual" install in package center but the file is "corrupt".
What the tips for DSM7 to install selfsigned/build package?
 

**Steps to reproduce**
Build the SPK, choose it as "manual install" in package center.
Error saying file in corrupted.
 
**Expected behavior**
I can install the SPK

**Synology NAS model**
DS918+

**Comment by vmpg** [comment]
additional step is required for the WireGuard package to start. This is related to preventing packages not signed by Synology from running with root privileges. When installing the package, uncheck the run after installation option. After installing the package, connect to the NAS via SSH and run the sudo /var/packages/WireGuard/scripts/start command.

> **Description**
> Hi, I maybe miss something, I'm able to build the SPK for DSM7/AppoloLake (for a DS918+ ).
> I build it from docker on my laptop because i got error with docker from the NAS itself.
> But then how to install it? I choose it from the "manual" install in package center but the file is "corrupt".
> What the tips for DSM7 to install selfsigned/build package?
> 
> **Steps to reproduce**
> Build the SPK, choose it as "manual install" in package center.
> Error saying file in corrupted.
> 
> **Expected behavior**
> I can install the SPK
> 
> **Synology NAS model**
> DS918+

additional step is required for the WireGuard package to start. This is related to preventing packages not signed by Synology from running with root privileges. When installing the package, uncheck the run after installation option. After installing the package, connect to the NAS via SSH and run the sudo /var/packages/WireGuard/scripts/start command.

**Comment by cyrinux** [comment]
Hi :) In fact, I can't I install the package at all for the moment. I understand that you describe the next step.

**Comment by Matige** [comment]
Try to install WireGuard from CLI:
```sh
sudo synopkg install WireGuard-<arch>-<version>.spk
sudo /var/packages/WireGuard/scripts/start
```
Of course, replace `<arch>` and `<version>` with the correct values.

**Comment by superslimjimmy** [comment]
Same issue here. I tried via CLI with:

`sudo synopkg install WireGuard-geminilake-1.0.20201221.spk`

and got the following error:

`{"error":{"code":0},"results":[{"action":"install","beta":false,"betaIncoming":false,"error":{"code":261,"description":"invalid package info content"},"installReboot":false,"installing":true,"language":"enu","last_stage":"prepare_install","package":"WireGuard","packageName":"WireGuard","spk":"WireGuard-geminilake-1.0.20201221.spk","stage":"install_failed","success":false,"username":""}],"success":false}`

**Comment by Matige** [comment]
@superslimjimmy Can you share your .spk file?

**Comment by cyrinux** [comment]
Hi guys,
From my side I got this:

```
nas#  /usr/syno/bin/synopkg install ~cyrinux/WireGuard-apollolake-1.0.20210606.spk
{"error":{"code":0},"results":[{"action":"install","beta":false,"betaIncoming":false,"error":{"code":261,"description":"package does not have preupgrade / postupgrade script"},"installReboot":false,"installing":true,"language":"enu","last_stage":"prepare_install","package":"WireGuard","packageName":"WireGuard","spk":"/var/services/homes/cyrinux/WireGuard-apollolake-1.0.20210606.spk","stage":"install_failed","success":false,"username":""}],"success":false}
```

**Comment by AverageHelper** [comment]
I'm seeing a similar issue:

```sh
$ sudo synopkg install WireGuard-geminilake-1.0.20201221.spk

{"error":{"code":0},"results":[{"action":"install","beta":false,"betaIncoming":false,"error":{"code":261,"description":"invalid package info content"},"installReboot":false,"installing":true,"language":"enu","last_stage":"prepare_install","package":"WireGuard","packageName":"WireGuard","spk":"WireGuard-geminilake-1.0.20201221.spk","stage":"install_failed","success":false,"username":""}],"success":false}
```

I'm trying to use the applicable SPK from the latest stable release: https://github.com/runfalk/synology-wireguard/releases/download/1.0.20201221/WireGuard-geminilake-1.0.20201221.spk

**Comment by ben-ba** [comment]
Hey guys, same here:

1st:

> sudo synopkg install WireGuard-avoton-1.0.20210606.spk 
>  {"error":{"code":0},"results":[{"action":"install","beta":false,"betaIncoming":false,"error":{"**code":0**},"finished":true,"installReboot":false,"installing":true,"language":"enu","last_stage":"postreplace","package":"WireGuard","packageName":"WireGuard","pid":23610,"spk":"WireGuard-avoton-1.0.20210606.spk","stage":"installed_and_stopped","status":"stop","success":true,"username":""}],"success":true}

Error Code 0

2nd:

> sudo synopkg install WireGuard-avoton-1.0.20210606.spk
> {"error":{"code":0},"results":[{"action":"install","beta":false,"betaIncoming":false,"error":{"_**code":261**_,"description":**"package does not have preupgrade / postupgrade script"**},"installReboot":false,"installing":true,"language":"enu","last_stage":"prepare_install","package":"WireGuard","packageName":"WireGuard","spk":"WireGuard-avoton-1.0.20210606.spk","stage":"install_failed","success":false,"username":""}],"success":false}

Error Code 261

System: DS1817+ avoton, DSM 7.0 sp
[WireGuard-avoton-1.0.20210606.spk.zip](https://github.com/runfalk/synology-wireguard/files/7181106/WireGuard-avoton-1.0.20210606.spk.zip)
k:

**Comment by ben-ba** [comment]
> Hi guys,
> From my side I got this:
> 
> ```
> nas#  /usr/syno/bin/synopkg install ~cyrinux/WireGuard-apollolake-1.0.20210606.spk
> {"error":{"code":0},"results":[{"action":"install","beta":false,"betaIncoming":false,"error":{"code":261,"description":"package does not have preupgrade / postupgrade script"},"installReboot":false,"installing":true,"language":"enu","last_stage":"prepare_install","package":"WireGuard","packageName":"WireGuard","spk":"/var/services/homes/cyrinux/WireGuard-apollolake-1.0.20210606.spk","stage":"install_failed","success":false,"username":""}],"success":false}
> ```

Seems that you have the same error as i;

Check if old versions of Wireguard.spk are gone:
`sudo synopkg list --name | grep WireGuard` 
if so; remove it
`sudo synopkg uninstall WireGuard`
rerun 
`sudo synopkg install WireGuard.spk`

**Comment by cyrinux** [comment]
@ben-ba this fix for me, was well the old package not well uninstall/still present but not display. Thanks a lot :)
